title: Convert-2-BIDS (fMRI Edition)
description: A step-by-step guide to teach the how and why behind modern neuroimaging preprocessing techniques
theme: just-the-docs

url: https://heuristicwondering.github.io/convert2BIDS-fMRI/

aux_links:
  Template Repository: https://github.com/heuristicwondering/convert2BIDS-fMRI

# Makes Aux links open in a new tab.
aux_links_new_tab: true

favicon_ico: /assets/images/favicon.svg

callouts:
  warning:
    title: Warning
    color: yellow