title: Convert-2-BIDS (fMRI Edition)
description: A step-by-step guide to teach the how and why behind modern neuroimaging preprocessing techniques
theme: just-the-docs

url: https://heuristicwondering.github.io/convert2BIDS-fMRI/

aux_links:
  Template Repository: https://github.com/heuristicwondering/convert2BIDS-fMRI

logo: ./assets/images/landing/benefit-of-using-BIDS.png

favicon_ico: "/assets/images/favicon.svg